json.id @product.id
json.name @product.name
json.price @product.price
json.description @product.description
json.discounted @product.is_discounted?
json.tax @product.tax
json.total @product.total
json.images @product.images
json.supplier @product.supplier